package edu.ithaca.dragon.par.domain;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class QuestionTest {

    @Test
    public void toJsonAndBackTest() throws IOException {
        Question planeQ = new Question("PlaneQ1", "On which plane is the ultrasound taken?", 1,
                "Lateral", Arrays.asList("Transverse", "Lateral", "I don't know"));
        Question structureQ = new Question("StructureQ1", "What structure is in the near field?", 2,
                "bone", Arrays.asList("bone", "ligament", "tumor", "tendon", "I don't know"));
        Question zoneQ = new Question("ZoneQ1", "In what zone is this ultrasound taken?", 4,
                "3c", Arrays.asList("1a", "1b", "2a", "2b", "2c", "3a", "3b", "3c"));
        List<Question> questionsToFile = Arrays.asList(planeQ, structureQ, zoneQ);

        JsonUtil.toJsonFile("src/test/resources/autoGenerated/QuestionTest-toJsonAndBackTest.json", questionsToFile);
        List<Question> questionsFromFile = JsonUtil.listFromJsonFile("src/test/resources/autoGenerated/QuestionTest-toJsonAndBackTest.json", Question.class);

        assertEquals(questionsToFile.size(), questionsFromFile.size());
        for (int i=0; i< questionsFromFile.size(); i++){
            assertEquals(questionsToFile.get(i), questionsFromFile.get(i));
        }
        Path path = Paths.get("src/test/resources/autoGenerated/QuestionTest-toJsonAndBackTest.json");
        assertTrue(Files.deleteIfExists(path));
    }

    @Test
    public void equalsTest(){
        Question planeQ = new Question("PlaneQ1", "On which plane is the ultrasound taken?", 1,
                "Lateral", Arrays.asList("Transverse", "Lateral", "I don't know"));
        assertEquals(planeQ, planeQ);
        assertNotEquals(planeQ, "Hello");

        Question planeQsame = new Question("PlaneQ1", "On which plane is the ultrasound taken?", 1,
                "Lateral", Arrays.asList("Transverse", "Lateral", "I don't know"));
        assertEquals(planeQ, planeQsame);

        Question planeQdiffAns = new Question("PlaneQ1", "On which plane is the ultrasound taken?", 1,
                "Lateral", Arrays.asList("Transverse", "Lateral", "I don't know too much"));
        assertNotEquals(planeQ, planeQdiffAns);
    }
}
