package edu.ithaca.dragon.par.authorModel;

import edu.ithaca.dragon.par.domainModel.QuestionPool;
import edu.ithaca.dragon.par.io.AuthorModelRecord;
import edu.ithaca.dragon.par.io.JsonQuestionPoolDatastore;
import edu.ithaca.dragon.par.studentModel.QuestionCount;
import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.InvalidParameterException;

import static junit.framework.TestCase.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class AuthorModelTest {

    private AuthorModel authorModel;
    private QuestionPool questionPool;

    @BeforeEach
    public void setUp() throws IOException {
        //TODO: the questionPool should load in questionTemplates
        questionPool = new QuestionPool(new JsonQuestionPoolDatastore("src/test/resources/author/DemoQuestionPoolFollowup.json").getAllQuestions());
        authorModel = new AuthorModel("TestAuthor1", QuestionCount.questionToQuestionCount(questionPool.getAllQuestions()));
    }

    @Test
    public void constructorTest() throws IOException {
        assertEquals("TestAuthor1", authorModel.getAuthorId());
        assertEquals(47, authorModel.getQuestionCountList().size());
    }

    @Test
    public void removeQuestionTest(){
        assertEquals(47, authorModel.getQuestionCountList().size());
        authorModel.removeQuestion("plane./images/demoEquine14.jpg");
        assertEquals(46, authorModel.getQuestionCountList().size());
        authorModel.removeQuestion("structure0./images/demoEquine02.jpg");
        assertEquals(45, authorModel.getQuestionCountList().size());

        assertThrows(InvalidParameterException.class, ()-> { authorModel.removeQuestion("ZoneQ3"); });
        assertThrows(InvalidParameterException.class, ()-> { authorModel.removeQuestion("NotAValidQuestionId"); });
    }

    @Test
    public void increaseTimesAttemptedTest(){
        assertEquals(0, authorModel.questionCountList.get(0).timesAttempted);
        authorModel.increaseTimesAttempted("plane./images/demoEquine14.jpg");
        assertEquals(1, authorModel.questionCountList.get(0).timesAttempted);
        authorModel.increaseTimesAttempted("plane./images/demoEquine14.jpg");
        assertEquals(2, authorModel.questionCountList.get(0).timesAttempted);

        assertEquals(0, authorModel.questionCountList.get(6).timesAttempted);
        authorModel.increaseTimesAttempted("structure0./images/demoEquine02.jpg");
        assertEquals(1, authorModel.questionCountList.get(6).timesAttempted);
        authorModel.increaseTimesAttempted("structure0./images/demoEquine02.jpg");
        assertEquals(2, authorModel.questionCountList.get(6).timesAttempted);


        assertEquals(0, authorModel.questionCountList.get(1).getFollowupCounts().get(0).timesAttempted);
        authorModel.increaseTimesAttempted("AttachQ1");
        System.out.println(authorModel.questionCountList.get(1).getFollowupCounts().get(0).getQuestion().getId());
        assertEquals(1, authorModel.questionCountList.get(1).getFollowupCounts().get(0).timesAttempted);
        authorModel.increaseTimesAttempted("AttachQ1");
        assertEquals(2, authorModel.questionCountList.get(1).getFollowupCounts().get(0).timesAttempted);


        assertThrows(InvalidParameterException.class, ()-> {authorModel.increaseTimesAttempted("NotAValidQuestionId");});
    }

    @Test
    public void toJsonAndBack() throws IOException{
        AuthorModelRecord authorModelRecord = new AuthorModelRecord(authorModel);
        JsonUtil.toJsonFile("src/test/resources/autoGenerated/AuthorModelRecordTest-toAndFromJsonTest.json", authorModelRecord);
        AuthorModelRecord authorModelRecordBack = JsonUtil.fromJsonFile("src/test/resources/autoGenerated/AuthorModelRecordTest-toAndFromJsonTest.json", AuthorModelRecord.class);
        AuthorModel authorModelBack = authorModelRecordBack.buildAuthorModel(questionPool);
        assertEquals(authorModel, authorModelBack);

        Path path = Paths.get("src/test/resources/autoGenerated/AuthorModelRecordTest-toAndFromJsonTest.json");
        assertTrue(Files.deleteIfExists(path));
    }


}
