package edu.ithaca.dragon.par.io;

import edu.ithaca.dragon.par.domainModel.QuestionPool;

import edu.ithaca.dragon.par.studentModel.ResponsesPerQuestion;
import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ResponsesPerQuestionRecordTest {
     @Test
    public void toJsonAndBackTest() throws IOException{
         QuestionPool qp = new QuestionPool(new JsonDatastore("src/test/resources/author/SampleQuestions2.json"));
         ResponsesPerQuestion response=new ResponsesPerQuestion("kandace",qp.getQuestionFromId("StructureQ2"),"hi");

         UserResponseRecord responseRecord=new UserResponseRecord(response);
         //write to Json
         JsonUtil.toJsonFile("src/test/resources/autoGenerated/ResponsesPerQuestionRecordTest-toJsonAndBackTest.json", responseRecord);
         // read
         UserResponseRecord record2=JsonUtil.fromJsonFile("src/test/resources/autoGenerated/ResponsesPerQuestionRecordTest-toJsonAndBackTest.json", UserResponseRecord.class);
         //
         ResponsesPerQuestion fromRecord= record2.buildUserResponse(qp);
         //
         assertEquals(response,fromRecord);

         Path path = Paths.get("src/test/resources/autoGenerated/ResponsesPerQuestionRecordTest-toJsonAndBackTest.json");
         assertTrue(Files.deleteIfExists(path));
     }
}
