package edu.ithaca.dragon.par.io;

import edu.ithaca.dragon.par.domainModel.QuestionPool;
import edu.ithaca.dragon.par.studentModel.StudentModel;
import edu.ithaca.dragon.util.JsonUtil;
import junit.framework.TestCase;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static junit.framework.TestCase.assertTrue;
import static org.junit.Assert.assertEquals;

public class StudentModelRecordTest {

    @Test
    public void toAndFromJsonTest() throws IOException {
        QuestionPool questionPool = new QuestionPool(new JsonDatastore("src/test/resources/author/SampleQuestions2.json"));
        StudentModel studentModel = new StudentModel("TestUser100", questionPool.getAllQuestions());

        //write to Json
        StudentModelRecord studentModelRecord = new StudentModelRecord(studentModel);
        JsonUtil.toJsonFile("src/test/resources/autoGenerated/StudentModelRecordTest-toAndFromJsonTest.json", studentModelRecord);

        //read
        StudentModelRecord studentModelRecordIn = JsonUtil.fromJsonFile("src/test/resources/autoGenerated/StudentModelRecordTest-toAndFromJsonTest.json", StudentModelRecord.class);
        StudentModel studentModelIn = studentModelRecordIn.buildStudentModel(questionPool);

        //compare
        assertEquals(studentModel, studentModelIn);

        Path path = Paths.get("src/test/resources/autoGenerated/StudentModelRecordTest-toAndFromJsonTest.json");
        Assertions.assertTrue(Files.deleteIfExists(path));
    }
}
