package edu.ithaca.dragon.par.io;

import edu.ithaca.dragon.par.domainModel.QuestionPool;
import edu.ithaca.dragon.par.studentModel.ResponsesPerQuestion;
import edu.ithaca.dragon.par.studentModel.StudentModel;
import edu.ithaca.dragon.par.studentModel.UserResponseSet;
import edu.ithaca.dragon.util.JsonUtil;
import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class StudentReportTest {

    @Test
    public void toAndFromJsonTest() throws IOException {
        List<ResponsesPerQuestion> responsesPerQuestions= JsonUtil.listFromJsonFile("src/test/resources/author/SampleResponsePerQuestionSet.json",ResponsesPerQuestion.class);
        UserResponseSet userResponseSet=new UserResponseSet(responsesPerQuestions.get(0).getUserId());
        for(ResponsesPerQuestion responsesPerQuestion:responsesPerQuestions){
            userResponseSet.addResponse(responsesPerQuestion);
        }
        QuestionPool questionPool = new QuestionPool(new JsonQuestionPoolDatastore("src/test/resources/author/SampleQuestionPoolWithAttachment.json").getAllQuestions());
        StudentModel studentModel1 = new StudentModel("TestUser-A", questionPool.getAllQuestions());
        StudentModel studentModel2 = new StudentModel("TestUser-B", questionPool.getAllQuestions());
        StudentModel studentModel3 = new StudentModel("TestUser-C", questionPool.getAllQuestions());
        StudentModel studentModel4 = new StudentModel("TestUser-D", questionPool.getAllQuestions());
        StudentModel studentModel5 = new StudentModel("TestUser-E", questionPool.getAllQuestions());
        List<StudentModel> allStudentModels=new ArrayList<>();
        allStudentModels.addAll(Arrays.asList(studentModel1,studentModel2,studentModel3,studentModel4,studentModel5));

        for(int i=0;i<allStudentModels.size();i++){
            allStudentModels.get(i).getUserResponseSet().setUserResponses(userResponseSet.getUserResponses());
        }
        List<StudentReport> studentReports=new ArrayList<>();
        for(StudentModel studentModel:allStudentModels){
            studentReports.add(studentModel.buildStudentReport(2));
        }
        //writes to Json
        JsonUtil.toJsonFile("src/test/resources/autoGenerated/SampleStudentReports.json", studentReports);
        //reads back in Json
        List<StudentReport> studentReportList = JsonUtil.listFromJsonFile("src/test/resources/autoGenerated/SampleStudentReports.json", StudentReport.class);

        assertEquals(5, studentReportList.size());
        Path path = Paths.get("src/test/resources/autoGenerated/SampleStudentReports.json");
        assertTrue(Files.deleteIfExists(path));
    }
}
