package edu.ithaca.dragon.par.io;

import edu.ithaca.dragon.par.domainModel.QuestionPool;
import edu.ithaca.dragon.par.studentModel.StudentModel;
import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

import static junit.framework.TestCase.assertTrue;
import static org.junit.Assert.assertEquals;

public class StudentModelRecordTest {

    @Test
    public void toAndFromJsonTest() throws IOException {
        QuestionPool questionPool = new QuestionPool(new JsonQuestionPoolDatastore("src/test/resources/author/SampleQuestionPool.json").getAllQuestions());
        StudentModel studentModel = new StudentModel("TestUser100", questionPool.getAllQuestions());

        //write to Json
        StudentModelRecord studentModelRecord = new StudentModelRecord(studentModel);
        JsonUtil.toJsonFile("src/test/resources/autoGenerated/StudentModelRecordTest-toAndFromJsonTest.json", studentModelRecord);

        //read
        StudentModelRecord studentModelRecordIn = JsonUtil.fromJsonFile("src/test/resources/autoGenerated/StudentModelRecordTest-toAndFromJsonTest.json", StudentModelRecord.class);
        StudentModel studentModelIn = studentModelRecordIn.buildStudentModel(questionPool);

        //compare
        assertEquals(studentModel, studentModelIn);

        Path path = Paths.get("src/test/resources/autoGenerated/StudentModelRecordTest-toAndFromJsonTest.json");
        Assertions.assertTrue(Files.deleteIfExists(path));
    }

    //TODO: CONVERT TO TEST READ AND WRITE
    public void busyModelToFile() throws IOException {
        QuestionPool questionPool = new QuestionPool(new JsonQuestionPoolDatastore("src/test/resources/author/SampleQuestionPool.json").getAllQuestions());
        StudentModel studentModel = new StudentModel("TestUser1", questionPool.getAllQuestions());
        List<ImageTaskResponse> responsesFromFile = JsonUtil.listFromJsonFile("src/test/resources/author/SampleResponses.json", ImageTaskResponse.class);
        ImageTaskResponse responseSet3=new ImageTaskResponse("response1", Arrays.asList("PlaneQ1","StructureQ1","ZoneQ1"),Arrays.asList("I'm","bad","student"));
        //terrible student
        studentModel.imageTaskResponseSubmitted(responsesFromFile.get(0),questionPool);
        studentModel.imageTaskResponseSubmitted(responsesFromFile.get(0),questionPool);
        for(int i=0;i<3;i++){
            studentModel.imageTaskResponseSubmitted(responseSet3,questionPool);
        }
        JsonUtil.toJsonFile("src/test/resources/author/SampleStudentModelBusy.json", Arrays.asList(new StudentModelRecord(studentModel)));
    }
}
