package edu.ithaca.dragon.par.io;

import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class TeacherReportTest {

    @Test
    public void toAndFromJsonTest()throws IOException {
        List<StudentReport> studentReportList = JsonUtil.listFromJsonFile("src/test/resources/author/SampleStudentReports.json", StudentReport.class);
        TeacherReport teacherReport=new TeacherReport(studentReportList);

        //writes to Json
        JsonUtil.toJsonFile("src/test/resources/autoGenerated/SampleTeacherReport.json", teacherReport);
        //reads back in Json
        TeacherReport teacherReport1 = JsonUtil.fromJsonFile("src/test/resources/autoGenerated/SampleTeacherReport.json", TeacherReport.class);

        assertEquals(5, teacherReport1.getStudentReports().size());

        Path path = Paths.get("src/test/resources/autoGenerated/SampleTeacherReport.json");
        assertTrue(Files.deleteIfExists(path));

    }


}
