package edu.ithaca.dragon.par.io;

import edu.ithaca.dragon.par.domainModel.QuestionPool;

import edu.ithaca.dragon.par.studentModel.UserResponse;
import edu.ithaca.dragon.util.JsonUtil;
import org.apache.catalina.User;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.Assert.assertEquals;

public class UserResponseRecordTest {
     @Test
    public void toJsonAndBackTest() throws IOException{
         QuestionPool qp = new QuestionPool(new JsonDatastore("src/test/resources/author/SampleQuestions2.json"));
         UserResponse response=new UserResponse("kandace",qp.getQuestionFromId("StructureQ2"),"hi");

         UserResponseRecord responseRecord=new UserResponseRecord(response);
         //write to Json
         JsonUtil.toJsonFile("src/test/resources/autoGenerated/UserResponseRecordTest-toJsonAndBackTest.json", responseRecord);
         // read
         UserResponseRecord record2=JsonUtil.fromJsonFile("src/test/resources/autoGenerated/UserResponseRecordTest-toJsonAndBackTest.json", UserResponseRecord.class);
         //
         UserResponse fromRecord= record2.buildUserResponse(qp);
         //
         assertEquals(response,fromRecord);
     }
}
