package edu.ithaca.dragon.par.deprecated.io;

import edu.ithaca.dragon.par.deprecated.domainModel.QuestionPool;
import edu.ithaca.dragon.par.deprecated.studentModel.ResponsesPerQuestion;
import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ResponsesPerQuestionRecordTest {
     @Test
    public void toJsonAndBackTest() throws IOException{
         QuestionPool qp = new QuestionPool(new JsonQuestionPoolDatastore("src/test/resources/author/questionPools/SampleQuestionPool.json").getAllQuestions());
         ResponsesPerQuestion response=new ResponsesPerQuestion("kandace",qp.getQuestionFromId("StructureQ2"),"hi");

         ResponsesPerQuestionRecord responseRecord=new ResponsesPerQuestionRecord(response);
         //write to Json
         JsonUtil.toJsonFile("src/test/resources/autoGenerated/ResponsesPerQuestionRecordTest-toJsonAndBackTest.json", responseRecord);
         // read
         ResponsesPerQuestionRecord record2=JsonUtil.fromJsonFile("src/test/resources/autoGenerated/ResponsesPerQuestionRecordTest-toJsonAndBackTest.json", ResponsesPerQuestionRecord.class);
         //
         ResponsesPerQuestion fromRecord= record2.buildResponsesPerQuestionRecord(qp);
         //
         assertEquals(response,fromRecord);

         Path path = Paths.get("src/test/resources/autoGenerated/ResponsesPerQuestionRecordTest-toJsonAndBackTest.json");
         assertTrue(Files.deleteIfExists(path));
     }
}
