package edu.ithaca.dragon.par.deprecated.io;

import edu.ithaca.dragon.par.deprecated.domainModel.QuestionPool;
import edu.ithaca.dragon.par.deprecated.studentModel.UserResponseSet;
import edu.ithaca.dragon.util.JsonUtil;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ResponsesPerQuestionSetRecordTest {
    @Test
    public void toJsonAndBackTest() throws IOException {
        List<ImageTaskResponseOOP> responsesFromFile = JsonUtil.listFromJsonFile("src/test/resources/author/responses/SampleResponses.json", ImageTaskResponseOOP.class);
        UserResponseSet que=new UserResponseSet(responsesFromFile.get(0).getUserId());
        QuestionPool qp = new QuestionPool(new JsonQuestionPoolDatastore("src/test/resources/author/questionPools/SampleQuestionPool.json").getAllQuestions());


        UserResponseSetRecord myURSR=new UserResponseSetRecord(que);

        //write to Json
        JsonUtil.toJsonFile("src/test/resources/autoGenerated/ResponsesPerQuestionSetRecordTest-toJsonAndBackTest.json",myURSR);
        //read from Json
        UserResponseSetRecord URSRFromJson=JsonUtil.fromJsonFile("src/test/resources/autoGenerated/ResponsesPerQuestionSetRecordTest-toJsonAndBackTest.json",UserResponseSetRecord.class);
        //make UserResponseSet from UserResponseSAetRecord
        UserResponseSet fromRecord=URSRFromJson.buildUserResponseSet(qp);
        //compare response sets
        assertEquals(que,fromRecord);

        Path path = Paths.get("src/test/resources/autoGenerated/ResponsesPerQuestionSetRecordTest-toJsonAndBackTest.json");
        assertTrue(Files.deleteIfExists(path));
    }
}
